version: "2.1"
services:
  druid:
    image: willioktavega/docker-druid:latest
    container_name: druid
    ports:
      - 8081:8081
      - 8082:8082
      - 8083:8083
      - 8888:8888

  superset:
    image: willioktavega/docker-superset:0.18.5
    container_name: superset
    ports:
      - 8088:8088
    volumes:
      - ./scripts/create_user.sh:/create_user.sh
    links:
      - druid:druid
    command: bash -c "/bin/chmod +x /create_user.sh && /create_user.sh && superset runserver"
    entrypoint: [""]
